### ISSUE TITLE
About the input frames of this code

### ISSUE THREAD

**Issue by Oceanlib** [ahmetakman/E-VFIA#2]
Hi, 
Thanks for your code, especially for the part related to the processing of bs_ergb.
But there may be a problem with the input frames of this code.  For example, in this code, I2, I3, I5, I6 are used as the inputs, and I4 is the intermediate frame to be interpolated. However, I2, I6 should also be the intermediate frames that are invisible when interpolating I4. The proper way is to take I1, I3, I5, I7, I9... as the inputs, and I2, I4, I6, I8... as the targets.
We hope that our judgment is wrong, but if it is not, this error may cause incorrect evaluation results reported in the paper.

**Comment by OnurSelim** [comment]
Hi Oceanlib,

I appreciate your interest in our code. The reason that we have used I2, I3, I5, and I6 is that it increases the number of data samples in evaluation. And the performance of our network for every interpolated image can be assessed individually. Therefore, using I2, I3, I5, and I6 does not cause incorrect evaluation results, but as you have stated, our code can not be directly used to create image-interpolated videos. 

This idea can also be seen in other papers. (For example, https://github.com/zhshi0816/Video-Frame-Interpolation-Transformer)

**Comment by Oceanlib** [comment]
Hi,
Thanks for your reply.  We are also familiar with VFIT. But, if you want to evaluate every frame in the test dataset, the interval of each input frame should be two. It means that you should use {I1, I3, I5, I7} as inputs for interpolating I4,  and {I2, I4, I6, I8} as inputs for estimating I5,  {I3, I5, I7, I9} for I6 and so on. It should not estimate I4 with {I2, I3, I5, I6} as inputs.
It can also be seen in the code of VFIT (dataset/Davis_test.py, line 20~21):
"""
add_files = ctg_imgs_[start_idx : start_idx+7 : 2]  \#please note that the step is 2
add_files = add_files[:2] + [ctg_imgs_[start_idx+3]] + add_files[2:]
"""
They also use {start_idx, start_idx+2, start_idx+4, start_idx+6} as inputs and [start_idx+3] as the target.
We think that {start_idx, start_idx+2, start_idx+4, start_idx+6}  is the correct interval of the low frame-rate inputs and {start_idx+1, start_idx+2, start_idx+4, start_idx+5} seems not proper.

**Comment by OnurSelim** [comment]
Hi Oceanlib,

Sorry about our confusion about VFIT. We understand that our setup is not ideal. However, even if we had used I0, I2, and I4, I6, the symmetry and attention mechanism should lead to a similar result. We will make additional tests and will give you updates ASAP. As you know, the images that are further from the target image contain much smaller information about the target image. Therefore, the results should be similar. 

Thank you for your inquiry.

**Comment by OnurSelim** [comment]
Hi @Oceanlib,
We (with @ahmetakman) have conducted a test to verify our expectations on this issue. We have arranged the inputs as you explained, where the I0, I2, I4, and I6 are used to find the target image, namely I3. The evaluation results came out as follows:

| PSNR (dB) 	|   SSIM   	|
|:---------:	|:--------:	|
| 32.242397 	| 0.957100 	|

As stated, as long as the inputs are symmetric, the proposed method finds the correct attention scores to generate the target image. What we mean by symmetry is that the distance between the frames on the right side is equal to the distance between the frames on the left side; also, the number of events on the right side is equal to the number of events on the event at left side. 

I hope this result makes the discussion clear.

**Comment by Oceanlib** [comment]
Thanks for your reply, and best wishes for your ICRA23.
