### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by wcz1124** [ahmetakman/E-VFIA#3]
The link to download the dataset crashed, I can't download the data, can you please send the dataset to my email：[wczhao24@gmail.com](https://contacts.google.com/?hl=zh_CN&pli=1),thank you very much

**Comment by ahmetakman** [comment]
Hello, the dataset link is broken from the source. So as soon as it is fixed I will update the link. The dataset does not belong to us therefore I am unable to send the data without permission.
